import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { QueryClientCustomProvider } from "@/modules/core/providers/QueryClientCustomProvider";
import { DiProvider } from "@/modules/core/contexts/DiContext";
import { ErrorBoundaryProvider } from "@/modules/core/providers/ErrorBoundaryProvider";
import { composeProviders } from "@/modules/core/utils/compose-providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Provider = composeProviders([
  ErrorBoundaryProvider,
  DiProvider,
  QueryClientCustomProvider,
]);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Toaster position="top-right" />
          {children}
        </Provider>
      </body>
    </html>
  );
}
